### ISSUE TITLE
Daily/weekly logging history

### ISSUE THREAD

**Issue by adistoica** [J-T-McC/uptime-backend-api#5] opened 2021-03-15 19:11 UTC
Hello,

Thank you for creating this nice package! I have a couple of questions:

- does it support daily or weekly logging for the downtime periods? I had a look at UptimeEventData#getWeeklyRangeCategory() but was unable to figure out what I need to use :)
- The email confirmation from your the demo doesn't seem to work.

**Comment by J-T-McC** [comment] 2021-03-15 20:24
Thanks for reporting that registration issue. I have pushed a fix. If you try to login again it should give you the option to request a new confirmation email which should do the trick on entry.

It was a bug caused by my experimenting with react native/expo. This project was mainly for learning the new Laravel auth options and creating a backed for my Vue3 composition API & react native learning. 

As for the charting, it initially started as weekly trends but I was impatient so I changed it to daily with the past 90 days pie. I don't have any imitate plans to add filtering options, but I may down the road. That weekly range category method is left over from the original weekly trend and meant to set the ISO 8601 date range for labels & tooltip.

I'm open to pull requests though if you do find a use for this and feel like contributing to it, but I felt the need to state this was mainly a learning project.

**Comment by J-T-McC** [comment] 2021-03-15 20:27
I also forgot to mention that each monitors events are stored in the event counts table and they give you the total uptime, downtime and recovery for a given day (UTC). With this you can get any trended period you want down to the day, it just needs to be added to the charting query logic.

**Closed** 2021-03-15 21:07 UTC

**Comment by adistoica** [comment] 2021-03-16 07:23
Thanks, all good now!
